#' Synthetic Racism and Civic Participation Survey
#'
#' A synthetic dataset of 150 individuals capturing experiences of
#' racism, policing, migration, and civic participation across
#' multiple demographic groups. Suitable for fairness auditing,
#' regression, binary, and multi-class classification.
#'
#' @format A tibble with 150 rows and 16 variables:
#' \describe{
#'   \item{age}{Integer. Age in years (18-75).}
#'   \item{gender}{Factor. male, female, diverse.}
#'   \item{hair_color}{Factor. blonde, brown, black, other.}
#'   \item{skin_color}{Factor. light, medium, dark.}
#'   \item{relationship_status}{Factor. single, engaged, married.}
#'   \item{racism_impact}{Integer 0-10. Perceived racism impact.}
#'   \item{police_stop}{Factor. 0 times, 1 time, 2 or more.}
#'   \item{migrant_status}{Factor. Yes or No.}
#'   \item{income}{Numeric. Monthly income (EUR).}
#'   \item{education_level}{Ordered factor. Education level.}
#'   \item{employment_status}{Factor. Employment category.}
#'   \item{area_type}{Factor. Urban or Rural.}
#'   \item{religion}{Factor. Religion category.}
#'   \item{language_proficiency}{Ordered factor. Language level.}
#'   \item{number_of_friends}{Integer 0-10.}
#'   \item{political_orientation}{Integer 0-3 (left to right).}
#' }
#' @source Synthetic data generated by the icarm team.
#' @examples
#' data(icarm_racism_survey)
#' m <- icarm_fit(racism_impact ~ ., icarm_racism_survey,
#'                model = "linear")
"icarm_racism_survey"

#' Synthetic Medical Readmission Dataset
#'
#' A synthetic dataset of 500 hospital patients with clinical
#' and administrative variables, designed for binary classification
#' (predicting 30-day readmission) and fairness auditing across
#' gender and insurance type.
#'
#' @format A tibble with 500 rows and 12 variables:
#' \describe{
#'   \item{age}{Integer. Patient age (18-90).}
#'   \item{gender}{Factor. male or female.}
#'   \item{bmi}{Numeric. Body mass index.}
#'   \item{systolic_bp}{Integer. Systolic blood pressure (mmHg).}
#'   \item{diastolic_bp}{Integer. Diastolic blood pressure (mmHg).}
#'   \item{glucose_level}{Integer. Fasting glucose (mg/dL).}
#'   \item{smoker}{Factor. Yes or No.}
#'   \item{diabetes}{Factor. Yes or No.}
#'   \item{insurance}{Factor. Public, Private, or None.}
#'   \item{num_prior_visits}{Integer. Prior hospital visits.}
#'   \item{length_of_stay}{Integer. Current stay in days.}
#'   \item{readmitted}{Factor. Yes (readmitted within 30 days) or No.}
#' }
#' @source Synthetic data generated by the icarm team.
#' @examples
#' data(icarm_medical)
#' m <- icarm_fit(readmitted ~ ., icarm_medical,
#'                model = "logistic", positive = "Yes")
"icarm_medical"

#' Synthetic Financial Loan Default Dataset
#'
#' A synthetic dataset of 1,000 loan applicants with financial
#' and demographic variables. Suitable for binary classification
#' (predicting loan default) and fairness auditing across gender
#' and ethnicity — a classic algorithmic fairness benchmark.
#'
#' @format A tibble with 1,000 rows and 12 variables:
#' \describe{
#'   \item{age}{Integer. Applicant age (20-75).}
#'   \item{income}{Numeric. Annual income (USD).}
#'   \item{credit_score}{Integer. Credit score (300-850).}
#'   \item{loan_amount}{Numeric. Requested loan amount (USD).}
#'   \item{loan_term}{Integer. Loan term in months.}
#'   \item{employment_status}{Factor. Employment category.}
#'   \item{home_owner}{Factor. Yes or No.}
#'   \item{num_accounts}{Integer. Number of credit accounts.}
#'   \item{debt_ratio}{Numeric. Debt-to-income ratio (0-1).}
#'   \item{gender}{Factor. male or female.}
#'   \item{ethnicity}{Factor. Ethnicity category.}
#'   \item{default}{Factor. Yes (defaulted) or No.}
#' }
#' @source Synthetic data generated by the icarm team.
#' @examples
#' data(icarm_financial)
#' m <- icarm_fit(default ~ credit_score + income +
#'                loan_amount + debt_ratio,
#'                icarm_financial, model = "logistic",
#'                positive = "Yes")
"icarm_financial"
